spring.application.name=AuthService

server.port=8081

spring.datasource.url=jdbc:postgresql://postgres:5432/AuthService
spring.datasource.username=postgres
spring.datasource.password=2004
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT Configuration
jwt.secret=bebfc1d8a791a0e1182ceac97af81421
jwt.access-token-validity=900
jwt.refresh-token-validity=2592000
jwt.issuer=auth-service

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Keycloak Configuration
spring.security.oauth2.client.registration.keycloak.client-id=auth-service
spring.security.oauth2.client.registration.keycloak.client-secret=4hv1gwk74Qx7T9NhXpLrw8nPSmFKrV7y
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email,roles
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://keycloak:8080/realms/master
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/master
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/master/protocol/openid-connect/certs

# Keycloak Admin Configuration
keycloak.auth-server-url=http://keycloak:8080
keycloak.realm=master
keycloak.resource=auth-service
keycloak.credentials.secret=4hv1gwk74Qx7T9NhXpLrw8nPSmFKrV7y
keycloak.use-resource-role-mappings=true
keycloak.bearer-only=true